### Использование exception

Допустим нам нужно протестировать в решении задачи, являетя ли d словарем.

Если нет - задание не должно засчитаться, несмотря на верный output

Для этого мы будем ронять выполнение кода через exception

    if type(d) != dict":
        raise Exception("Объект d должен быть словарем!")
        
Если таких условий много, удобно структурироваться и использовать функцию

    def xcheck(value,clue,message): 
        if value != clue:
            raise Exception(message)
        
Теперь наша проверка будет устроена так:

    xcheck(type(d), dict, "Объект d должен быть словарем!")
    
Добавим еще несколько примеров

    xcheck(type(d), dict, "Объект d должен быть словарем!")
    xcheck(len(d), 7, "В словаре должно быть 4 элемента")      
    xcheck(d.get("а"), 7, "В словаре d по ключу a должно храниться значение 7")
  
    
